#!/usr/bin/env bash

# THIS SCRIPT CURRENTLY DOES NOT WORK.
# -- Currently rewriting to implement new options.

# TODO
# ===========
# [ inwork ] reorganize current codebase (will be inwork until finished)
# [ inwork ] implement debug verbosity (will be inwork until finished)
# [  done  ] write parse_args
# [  done  ] check number of args passed
# [  done  ] sanitize FQDN
# [  done  ] import finish, debug, version functions
# [  done  ] hook imported functions into parse_args
# [  done  ] utilize finish for all error exits
# [  todo  ] prereqs - check for all needed commands, prompt to install? i.e. mysql
# [  done  ] prereqs - check for needed files, prompt to install? i.e. wordpress
# [ inwork ] inputs - need to separate wordpress settings from database settings
# [ inwork ] utilize associative array for wordpress settings
# [  todo  ] destroy - pull db configs from file to destroy
# ==========
# [   53%  ] - v0.7.0


# This script is versioned with Semantic Versioning. https://semver.org
readonly VERSION="0.7.0"
# Errors
readonly ERR_UNK_OPT="64"
readonly ERR_TOO_MANY_ARGS="65"
readonly ERR_NO_FQDN="66"
readonly ERR_MUST_BE_ROOT="67"
readonly ERR_INVALID_FQDN="68"
readonly ERR_DOMAIN_UNREACHABLE="69"
readonly ERR_NO_WORDPRESS="70"
readonly ERR_NO_MYSQL="71"
readonly ERR_CONFIG_EXISTS="72"
readonly ERR_MYSQL_SETTINGS_NOT_AVAILABLE="73"
readonly ERR_MYSQL_USER_TOO_LONG="74"
readonly ERR_MYSQL_DB_TOO_LONG="75"
readonly ERR_MYSQL_INVALID_CHAR="76"
readonly ERR_NO_ARG_GIVEN="77"
readonly ERR_CONFIG_MISMATCH="78"
# Script-specific constants
readonly WP_CONTENT_DIR_ORIG="/var/lib/wordpress/wp-content"
readonly WP_CONTENT_SRV_DIR="/srv/www/wp-content"
readonly WP_ETC_DIR="/etc/wordpress"
readonly FQDN_VALID="^([a-zA-Z0-9][a-zA-Z0-9-]{0,61}[a-zA-Z0-9]\.)+[a-zA-Z]{2,}$"
readonly PASSWD_GEN=",.[]<>:{}!@$^&*()_+-=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

# Colors
readonly ANSI_RED="\033[1;31m"
readonly ANSI_CLEAR="\033[0m"
readonly ANSI_YELLOW="\033[1;93m"
# Unset boolean/control vars
unset DEBUG
unset BACKUP
unset DESTROY
unset WP_CONFIG
# Define vars
ARGS=()
TAGLINE="# Created by $0"
declare -A WP_CONFIG
# DB_NAME - passed at cli, or generated from fqdn
# DB_USER - passed at cli, or generated from fqdn - DIFFERENT from dbadmin
# DB_PASSWORD - Generated? or allow user to set at cli
# DB_HOST - passed at cli, or assumed localhost
# SECRET_KEY - Generated
# WP_CONTENT_DIR - Generated from FQDN

finish () {
    local rc="$1"
    shift
    local msg="$@"
    if [[ "${rc}" -gt 0 ]]; then
        printf "${ANSI_RED}%s: %s${ANSI_CLEAR}\n" "$(basename $0)" "${msg}"
        printf "Try: $(basename $0) -h\n"
    fi
    exit "${rc}"
} >&2

debug () {
    local msg="$@"
    if [[ "${DEBUG}" ]]; then
        printf "${ANSI_YELLOW}[-]${ANSI_CLEAR} %s\n" "${msg}" >&2
    fi
}

version () {
    printf "${VERSION}\n"
}

usage() {
cat <<EOF
$0 [-h | -d | -b] [-n NAME | -e DB Name] [-u MySQL user] [-t MySQL host] FQDN

Creates by default a Wordpress mysql configuration depending on required fully
qualified domain name (FQDN).

Options:
    -h          show this help and exit
    -v          increase verbosity
    -d          destroy named site and purge
    -b          backup named site

Wordpress Settings: (auto-generated if not given)
    -n NAME     mysql database name for this wordpress instance
    -u USER     mysql username for this wordpress instance
    -p PASS     mysql password for this wordpress instance

Database Settings: (assumed localhost/root/no password if not given)
    -N HOST     mysql server hostname (for non-standard database)
    -U USER     mysql admin username (for non-standard database)
    -P PASS     mysql admin password (for non-standard database)

Example: You want your blog to be served from http://blog.example.com
         for user 'wordpress'.

Then run:
sudo bash $0 -n wordpress blog.example.com

EOF
}

generate_password () {
    local length="$1"
    local password=
    while [[ "${n:=1}" -le "${length}" ]]; do
        password="${password}${PASSWD_GEN:$(($RANDOM%${#PASSWD_GEN})):1}"
        let n+=1
    done
    printf "${password}"
}


checkforexistingsetup() {
    if [ -f $CONFIG_FILE ] ; then
        echo WARNING: $CONFIG_FILE exists!
        finish "${ERR_CONFIG_EXISTS}" "config exists: ${CONFIG_FILE}"
    fi
    
    # Generate a random password without Perl
    # MATRIX=",.[]<>:{}!@$^&*()_+-=0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    if [ ! $MYSQLUSER ]; then
        LENGTH="8"
        while [ "${n:=1}" -le "$LENGTH" ]
        do
            DB_PASSWORD="$DB_PASSWORD${PASSWD_GEN:$(($RANDOM%${#PASSWD_GEN})):1}"
            let n+=1
        done
        DB_USER=$NAME
    else
        DB_USER=$MYSQLUSER
        echo "Enter MySQL password for user $DB_USER."
        read -p "> " DB_PASSWORD
    fi
    
    LENGTH="50"
    while [ "${n:=1}" -le "$LENGTH" ]
    do
        SECRET_KEY="$SECRET_KEY${PASSWD_GEN:$(($RANDOM%${#PASSWD_GEN})):1}"
        let n+=1
    done
    
    if [ ! $DB_DB ]; then
        DB_NAME=$NAME
    else
        DB_NAME=$DB_DB
    fi

    # Write the config file for wordpress

    # REPLACEMENT CODE TO BE USED WHEN ASSOCIATIVE ARRAY IS WORKING
    # CONFIG_DATA="<?php\n"
    # CONFIG_DATA="${CONFIG_DATA}# Created by $0\n"
    # for key in ${WP_CONFIG[@]}; do
    #     CONFIG_DATA="${CONFIG_DATA}    define('${key}', '${WP_CONFIG[key]}');\n"
    # done
    # CONFIG_DATA="${CONFIG_DATA}    define('FS_METHOD', 'direct');\n"
    # CONFIG_DATA="${CONFIG_DATA}?>\n"
    # printf "${CONFIG_DATA}" > "${CONFIG_FILE}"

    printf "<?php\n" >> $CONFIG_FILE
    printf "# Created by $0\n" >> $CONFIG_FILE
    printf "define('DB_NAME', '$DB_NAME');\n" >> $CONFIG_FILE
    printf "define('DB_USER', '$DB_USER');\n" >> $CONFIG_FILE
    printf "define('DB_PASSWORD', '$DB_PASSWORD');\n" >> $CONFIG_FILE
    printf "define('DB_HOST', '$DB_HOST');\n" >> $CONFIG_FILE
    printf "define('SECRET_KEY', '$SECRET_KEY');\n" >> $CONFIG_FILE
    printf "define('WP_CONTENT_DIR', '$CONTENT');\n" >> $CONFIG_FILE
    printf "define('FS_METHOD', 'direct');\n" >> $CONFIG_FILE
    printf "?>\n" >> $CONFIG_FILE
    # REPLACEMENT CODE ENDS HERE

    # Set permissions
    chmod 640 "${CONFIG_FILE}"
    chgrp www-data "${CONFIG_FILE}"
    echo $CONFIG_FILE written
}

create() {
# Create the database and user
# Wordpress's install.php creates the tables btw
if [ ! $DB_DB ]; then
    MYSQLCOMMAND="mysql -u $DB_USER -p -h $DB_HOST"
    $MYSQLCOMMAND <<EOF
CREATE DATABASE $NAME;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
ON $DB_NAME.*
TO $DB_USER@$DB_HOST
IDENTIFIED BY '$DB_PASSWORD';
FLUSH PRIVILEGES;
EOF
fi

echo Goto http://$DOMAIN to setup Wordpress
}

backup() {
echo Enter root password for mysql:
BACKUPFILE=/tmp/blog-$NAME.bak.sql.bz2
mysqldump --add-drop-table -u root -p $NAME | bzip2 -c > $BACKUPFILE && echo Wrote $BACKUPFILE
}

destroy() {
# The destroy method need root to be able to drop databases and such.
# People using complex setups with remote servers probably know how to
# cleanup after the user any way.
if [ ! -e /etc/mysql/debian.cnf ]; then
    finish "${ERR_MYSQL_SETTINGS_NOT_AVAILABLE}" "manual database cleanup required"
fi
echo Destroying $NAME
prompt
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
CONNECT mysql;
DELETE FROM user where user='$NAME';
DELETE FROM db WHERE User = '$NAME';
DELETE FROM tables_priv WHERE User = '$NAME';
DELETE FROM columns_priv WHERE User = '$NAME';
FLUSH PRIVILEGES ;
DROP DATABASE IF EXISTS $NAME;
EOF
rm $CONFIG_FILE
}

prompt() {
while true; do
  echo -n "Are you sure? (y/n) "
  read yn
  case $yn in
    y* | Y* ) break ;;
    [nN]* )   finish "0" "" ; break ;;
    * ) echo "unknown response.  Asking again" ;;
  esac
done
}


parse_args () {

    optstring=":hbdn:u:p:N:U:P:vV"

    while [[ ${OPTIND} -le "$#" ]]; do
        if getopts ${optstring} arg; then
            case ${arg} in
                h) usage; finish 0 "" ;;
                b) BACKUP=1 ;;
                d) DESTROY=1 ;;
                n) WP_DB_NAME="${OPTARG}" ;;
                u) WP_DB_USER="${OPTARG}" ;;
                p) WP_DB_PASS="${OPTARG}" ;;
                N) MYSQL_HOST="${OPTARG}" ;;
                U) MYSQL_USER="${OPTARG}" ;;
                P) MYSQL_PASS="${OPTARG}" ;;
                v) DEBUG=yes ;;
                V) version; finish 0 "" ;;
                *) finish "${ERR_UNK_OPT}" "unknown option: -${OPTARG}" ;;
            esac
        else
            ARGS+=("${!OPTIND}")
            ((OPTIND++))
        fi    
    done

    debug "testing FQDN: ${ARGS[@]} ..."
    debug "... is there one?"
    if [[ ${#ARGS[@]} -lt 1 ]]; then
        finish $ERR_NO_FQDN "no FQDN given"
    fi
    debug "... is there too many?"
    if [[ ${#ARGS[@]} -gt 1 ]]; then
        finish "${ERR_TOO_MANY_ARGS}" "too many arguments: ${ARGS[@]}"
    fi
    debug "... is it valid?"
    if [[ ! "${ARGS[0]}" =~ $FQDN_VALID ]]; then
        finish "${ERR_INVALID_FQDN}" "invalid FQDN given: ${ARGS[0]}"
    fi
}


mksrvdir () {
    local content_dir="$1"
    if [[ ! -d "${WP_CONTENT_SRV_DIR}" ]]; then mkdir -p "${WP_CONTENT_SRV_DIR}"; fi
    cp -r "${WP_CONTENT_DIR_ORIG}" "${WP_CONTENT_SRV_DIR}/${content_dir}"    
}

mysql_cmd () {
    :
}


read_config () {
    local domain="$1"
    if [[ ! "${domain}" ]]; then finish "${ERR_NO_ARG_GIVEN}" "no domain given to pull config"; fi
    cfgfile="${WP_ETC_DIR}/config-${domain}.php"
    debug "attempting pull of config for ${domain} - ${cfgfile}"
    if [[ "$(grep '\#' ${cfgfile})" != "${TAGLINE}" ]]; then
        finish "${ERR_CONFIG_MISMATCH}" "config specified not written by this script"
    fi
    while read -r line ; do
        if [[ "${line}" =~ '#' ]] || [[ "${line}" =~ "?" ]]; then
            :
        else
            local key=$(echo "$line" | cut -d "'" -f 2)
            local value=$(echo "$line" | cut -d "'" -f 4)
            WP_CONFIG[$key]="${value}"
            debug "set $key to ${WP_CONFIG[$key]}"
        fi
    done < "${cfgfile}"

}


main() {
    parse_args "$@"

# WP_CONTENT[key] = "${value}"
# 'DB_NAME'      # WP_DB_NAME
# 'DB_USER'      # WP_DB_USER
# 'DB_PASSWORD   # WP_DB_PASS
# 'DB_HOST'      # MYSQL_HOST
# 'SECRET_KEY'
# 'WP_CONTENT_DIR'

# MYSQL_USER
# MYSQL_PASS

    DOMAIN=$(echo "${ARGS[0]}" | tr "[:upper:]" "[:lower:]")
    
    local name=$(echo $DOMAIN | sed 's,\.,,g;s,-,,g')

    # Set / Check WP Database
    if [[ ! "${WP_DB_NAME}" ]] ; then
        debug "wordpress database name not given..."
        WP_DB_NAME="${name}"
        debug "...generated from FQDN: ${WP_DB_NAME}"
    fi
    if [[ "${#WP_DB_NAME}" -gt 64 ]]; then finish "${ERR_MYSQL_DB_TOO_LONG}" \
        "database name too long - consider setting with -n"; fi
    if [[ "${WP_DB_NAME}" =~ [^a-zA-Z0-9\-\_]+ ]]; then finish "${ERR_MYSQL_INVALID_CHAR}" \
        "database name invalid character (not all alphanumeric)"; fi
    WP_CONFIG[DB_NAME]="${WP_DB_NAME}"
    debug "set WP_CONFIG[DB_NAME] to ${WP_DB_NAME}"

    # Set / Check WP User
    if [[ ! "${WP_DB_USER}" ]]; then
        debug "wordpress database user not given..."
        WP_DB_USER="${name}"
        debug "...generated from FQDN: ${WP_DB_USER}"
    fi
    if [[ "${#WP_DB_USER}" -gt 32 ]]; then finish "${ERR_MYSQL_USER_TOO_LONG}" \
        "database name too long - consider setting with -n"; fi
    if [[ "${WP_DB_USER}" =~ [^a-zA-Z0-9\-\_]+ ]]; then finish "${ERR_MYSQL_INVALID_CHAR}" \
        "database user invalid character (not all alphanumeric)"; fi
    WP_CONFIG[DB_USER]="${WP_DB_USER}"
    debug "set WP_CONFIG[DB_USER] to ${WP_DB_USER}"


    echo "testing read_config"
    read_config $DOMAIN
    exit 0

    if [ ! $DB_HOST ]; then
        DB_HOST="localhost"
    fi




    CONTENT="/var/lib/wordpress/wp-content"
    CONFIG_FILE=/etc/wordpress/config-$DOMAIN.php

    if [ $BACKUP ] ; then
        backup
        finish "0" ""
    fi
    
    if [ $DESTROY ] ; then
        destroy
        finish "0" ""
    fi

    checkforexistingsetup
    create
 }



# prereqs
if [[ "$(id -u)" != "0" ]]; then finish "${ERR_MUST_BE_ROOT}" "must be root"; fi
if [[ ! -d "${WP_ETC_DIR}" ]]; then finish "${ERR_NO_WORDPRESS}" "${WP_ETC_DIR} not found - is wordpress installed?"; fi
if [[ ! -d "${WP_CONTENT_DIR_ORIG}" ]]; then finish "${ERR_NO_WORDPRESS}" "${WP_CONTENT_DIR_ORIG} not found - is wordpress installed?"; fi
MYSQL=$(which mysql) || finish "${ERR_NO_MYSQL}" "mysql not found - is mysql-client installed?"

if [[ $(basename $0) == "setup-multisite" ]]; then main "$@"; fi
